### ISSUE TITLE
error on fresh project

### ISSUE THREAD

**Issue by VicVibesPL** [ilikerobots/cookiecutter-vue-django#87]
![image](https://github.com/ilikerobots/cookiecutter-vue-django/assets/11517372/132ef13e-6759-4276-8e7a-a4480e7c779e)

running with docker compose -f local.yml up

**Comment by AMR1798** [comment]
check your INSTALLED_APPS list, see if `django_vue_utilities` is included. By default it was not included. Probably due to default settings provided by cookiecutter.

**Comment by ilikerobots** [comment]
> check your INSTALLED_APPS list, see if `django_vue_utilities` is included. By default it was not included. Probably due to default settings provided by cookiecutter.  

@AMR1798 thanks. I'll take a look tomorrow and get this fixed up

**Comment by ilikerobots** [comment]
@wiktorcie :  Addressed in https://github.com/ilikerobots/cookiecutter-vue-django/commit/b5db3e025388c9b61ae96891a0401868a3b60447.  

Let me know if any further problems.
