### ISSUE TITLE
How are you loading non CSS assets?

### ISSUE THREAD

**Issue by dylanjcastillo** [ilikerobots/cookiecutter-vue-django#89]
I noticed that non-CSS assets in the frontend `assets/` folder didn't load correctly.

To make it work I included those assets in the `static` folder in the backend application and used the `inject` approach as follows (for `logo.svg`):

**Django template: home.html**
```html
{% extends "_base.html" %}
{% load vue_utils %}
{% load static %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
    <div id="app"></div>
{% endblock content %}
{% block scripts %}
    <script type="module" crossorigin src="{% vue_bundle_url 'main' %}"></script>
    {% static 'logo.svg' as logoSvg %}
    {% vue_provide 'logoSvg' logoSvg %}
{% endblock scripts %}
```

**Vue: app.vue**
```vue
<script setup>
import { inject } from "vue";
import HelloWorld from "./components/HelloWorld.vue";
import TheWelcome from "./components/TheWelcome.vue";

const logoSvg = inject('logoSvg');
</script>

<template>
  <header>
    <img alt="Vue logo" class="logo" :src="logoSvg" width="125" height="125" />
    <div >
      <HelloWorld msg="HAHAHA" />
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>

<style scoped>
</style>
```

But I was wondering if there's a better way to handle this. Are you following a similar approach or doing something else?

Again, thank you. I got burned using HTMX I was looking for a solution that provided a way to easily encapsulate the frontend in components and not have to use a REST backend service.

**Comment by ilikerobots** [comment]
That's one of the two best ways to do it, as far as I have discovered thus far.  The other way is to use the "psuedoSlot" approach, where you would add a [tag inside your template root element](https://github.com/ilikerobots/cookiecutter-vue-django/blob/c5df57c2ba7fbd9c33b6e33bd0ced44a8a3d9218/%7B%7Bcookiecutter.project_slug%7D%7D/rewards/templates/rewards/list.html#L15-L19) and then [re-render it in your component](https://github.com/ilikerobots/cookiecutter-vue-django/blob/c5df57c2ba7fbd9c33b6e33bd0ced44a8a3d9218/%7B%7Bcookiecutter.project_slug%7D%7D/vue_frontend/src/components/PointsStatus.vue#L43).  This [depends on some code to attach these "pseudo-slots"](https://github.com/ilikerobots/vue-plugin-django-utils/blob/057c35f9c29abb018bae21e1950f1396084d9381/src/DjangoUtils.ts#L12-L19), which you can roll yourself or I've made it available as part of [vue-plugin-django-utils](https://github.com/ilikerobots/vue-plugin-django-utils)

This would allow you to do something like:
```html
{% extends "_base.html" %}
{% load vue_utils %}
{% load static %}
{% block title %}
    Home
{% endblock title %}
{% block content %}
    <div id="app"> 
        <img src="{% static 'logo.svg' %}"  
                 alt="Vue logo" class="logo" width="125" height="125" 
                 data-django-slot="logoSvg">
    </div>
{% endblock content %}
{% block scripts %}
    <script type="module" crossorigin src="{% vue_bundle_url 'main' %}"></script>
{% endblock scripts %}
```
```js
<script setup>
import HelloWorld from "./components/HelloWorld.vue";
import TheWelcome from "./components/TheWelcome.vue";
</script>

<template>
  <header>
    <span v-html="$djangoSlots.logoSvg"></span>
    <div >
      <HelloWorld msg="HAHAHA" />
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>
```

Thanks for the kind words!
