### ISSUE TITLE
stops when choosing no cloud_provider nor whitenoise

### ISSUE THREAD

**Issue by nerdoc** [ilikerobots/cookiecutter-vue-django#9]
## What happened?
It stopped after I didn't choose a cloud_provider, and NOT whitenoise. Didn't know that and had to do all the steps again.

## What should've happened instead?
sane defaults. If there is chosen "None" as cloud_provider, whitenoise should be "y" per default.

## Steps to reproduce

1. choose "None" as cloud_provider
1. choose (default) "n" at use_whitenoise
1. it stops with an error:

```
You should either use Whitenoise or select a Cloud Provider to serve static files
ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by ilikerobots** [comment]
Hi, thanks for the report! In this case, though, this is the how the upstream [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) works.  My goal is to keep this repo as similar to that repo as possible, except for the addition of Vue.

This issue would best be refiled at that repo.  If it's fixed there, it will be included here as well next time I sync.
